#!/usr/bin/env python3
"""
fix-douai-refs-v3.py
Re-match Douai 1609 annotation refs using 1609-spelling verse sources.
v3 changes vs v2:
  - Tighter VerseQuote split: first sentence only, hard cap 20 words
  - Stricter cross-book thresholds: 0.40 (vs 0.25 in v2)
  - Modern DRB thresholds raised: same-book 0.35, cross-book 0.50
  - Checkpoint every 200 rows; abort if >70% LOW_CONFIDENCE in window
  - Abbreviation normalization (2Sm→2Sam etc.)
  - Outputs as v3 files (does NOT overwrite v2)

Source priority (per SOURCES.md):
  1. drb-1609-saint-dismas.tsv  — TeX PDFs
  2. drb-1609-originaldouay.tsv — HTML
  3. drb-1609-pdf.tsv           — OCR
  4. drb.tsv                    — Modern DRB, match-only (no text output)

CRITICAL: drb.tsv text NEVER appears in output. Only used to identify book/ch/v.
          Output VerseQuote and Commentary are ALWAYS the annotation's own original text.

Inputs:  douai-1609-clean.tsv  (or .bak.tsv if exists)
Output:  douai-1609-fixed-v3.tsv
         douai-1609-fix-report-v3.txt
         douai-1609-compare-v3.txt  (generated by compare-douai-v3.py)
"""

import re
import sys
import shutil
import os
from collections import defaultdict, Counter

HERE     = os.path.dirname(os.path.abspath(__file__))
INPUT    = os.path.join(HERE, "douai-1609-clean.tsv")
BAK      = os.path.join(HERE, "douai-1609-clean.bak.tsv")
OUTPUT   = os.path.join(HERE, "douai-1609-fixed-v3.tsv")
REPORT   = os.path.join(HERE, "douai-1609-fix-report-v3.txt")

SRC_SD   = os.path.join(HERE, "drb-1609-saint-dismas.tsv")   # Source 1
SRC_ODR  = os.path.join(HERE, "drb-1609-originaldouay.tsv")  # Source 2
SRC_PDF  = os.path.join(HERE, "drb-1609-pdf.tsv")            # Source 3
SRC_DRB  = os.path.join(HERE, "drb.tsv")                     # Source 4 — match only

# v3 thresholds
THRESH_SD_SAME   = 0.25   # same-book, sources 1–2
THRESH_SD_CROSS  = 0.40   # cross-book, sources 1–2
THRESH_ODR_SAME  = 0.25
THRESH_ODR_CROSS = 0.40
THRESH_PDF_SAME  = 0.25   # PDF: same-book slightly higher than v2 (was 0.22)
THRESH_PDF_CROSS = 0.40
THRESH_DRB_SAME  = 0.35   # modern DRB: same-book
THRESH_DRB_CROSS = 0.50   # modern DRB: cross-book — hardest to earn

CHECKPOINT   = 200
ABORT_FRAC   = 0.70   # v3: 70% (v2 was 60%)
QUOTE_MAX_W  = 20     # v3: max 20 words (v2 was 30)

# ═══════════════════════════════════════════════════════════════════════════════
# Abbreviation normalization (v3 fix)
# ═══════════════════════════════════════════════════════════════════════════════

ABBREV_FIX = {
    '2Sm':   '2Sam',
    '2Kgs':  '2Kings',
    '1Sm':   '1Sam',
    '1Pt':   '1Pet',
    '2Pt':   '2Pet',
    '1Tm':   '1Tim',
    '2Tm':   '2Tim',
    '1Kgs':  '1Kings',
    'Hb':    'Heb',
}

def fix_abbrev(abbrev: str) -> str:
    return ABBREV_FIX.get(abbrev, abbrev)


# ═══════════════════════════════════════════════════════════════════════════════
# Normalization
# ═══════════════════════════════════════════════════════════════════════════════

LONG_S = str.maketrans({
    'ſ': 's', '\u017f': 's', 'ꝉ': 'l', 'ꝛ': 'r',
})

SPELL_MAP = {
    'fhall': 'shall', 'fhal': 'shall', 'thal': 'shall', 'inal': 'shall',
    'fhould': 'should', 'fhew': 'shew', 'faid': 'said', 'faw': 'saw',
    'fonne': 'sonne', 'fome': 'some', 'fuch': 'such', 'felf': 'self',
    'felues': 'selues', 'fix': 'six', 'fince': 'since', 'firft': 'first',
    'fecond': 'second', 'ftand': 'stand', 'ftrong': 'strong',
    'ftrength': 'strength', 'ftone': 'stone', 'fword': 'sword',
    'fpirit': 'spirit', 'fpake': 'spake', 'fpoken': 'spoken',
    'fpeake': 'speake', 'fpread': 'spread', 'fruite': 'fruite',
    'fhore': 'shore', 'fhed': 'shed', 'fhepe': 'shepe', 'fhepe': 'sheepe',
    'vp': 'up', 'vnto': 'unto', 'vpon': 'upon', 'vntil': 'until',
    'vnder': 'under', 'vfe': 'use', 'vs': 'us',
    'wil': 'wil', 'shal': 'shall',
}

BOOK_ALIAS = {
    'Apc': 'Rev',
}


def normalize(text: str) -> list:
    """Lowercase, remove punctuation, apply spelling map. Return word list."""
    text = text.translate(LONG_S)
    text = text.lower()
    text = re.sub(r"[^\w\s']", ' ', text)
    text = re.sub(r'\b\d+\b', '', text)
    words = text.split()
    result = []
    for w in words:
        w = SPELL_MAP.get(w, w)
        if len(w) >= 2:
            result.append(w)
    return result


def jaccard(a: list, b: list) -> float:
    if not a or not b:
        return 0.0
    sa, sb = set(a), set(b)
    inter = len(sa & sb)
    union = len(sa | sb)
    return inter / union if union else 0.0


# ═══════════════════════════════════════════════════════════════════════════════
# Verse loading
# ═══════════════════════════════════════════════════════════════════════════════

def load_1609_tsv(path) -> dict:
    """Load 1609 TSV → {(abbrev,ch,v): (raw_text, norm_words)}"""
    verses = {}
    if not os.path.exists(path):
        print(f"  SKIP: {os.path.basename(path)} not found", file=sys.stderr)
        return verses
    with open(path, encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i == 0:
                continue
            parts = line.rstrip('\n').split('\t')
            if len(parts) < 4:
                continue
            abbrev, ch_s, v_s, text = parts[0], parts[1], parts[2], parts[3]
            try:
                ch, v = int(ch_s), int(v_s)
            except ValueError:
                continue
            # Normalize abbrev in source as well
            abbrev = fix_abbrev(abbrev)
            key = (abbrev, ch, v)
            if key not in verses:
                verses[key] = (text, normalize(text))
    return verses


def load_modern_drb(path) -> dict:
    """Load modern DRB → {(abbrev,ch,v): norm_words}  — NO raw text stored."""
    verses = {}
    if not os.path.exists(path):
        print(f"  SKIP: {os.path.basename(path)} not found", file=sys.stderr)
        return verses
    with open(path, encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i == 0:
                continue
            parts = line.rstrip('\n').split('\t')
            if len(parts) < 6:
                continue
            abbrev, ch_s, v_s, text = parts[1], parts[3], parts[4], parts[5]
            try:
                ch, v = int(ch_s), int(v_s)
            except ValueError:
                continue
            abbrev = fix_abbrev(abbrev)
            key = (abbrev, ch, v)
            if key not in verses:
                verses[key] = normalize(text)
    return verses


def build_index(verses: dict) -> dict:
    """word → frozenset of verse keys (inverted index)."""
    idx = defaultdict(set)
    for key, val in verses.items():
        words = val[1] if isinstance(val, tuple) else val
        for w in set(words):
            idx[w].add(key)
    return idx


def books_in_source(verses: dict) -> set:
    """Return set of book abbreviations present in this source."""
    return {key[0] for key in verses.keys()}


def best_match(query_words, orig_book, verses, index, thresh_same, thresh_cross):
    """
    Return (best_key, best_score) or (None, 0.0).
    Applies different thresholds for same-book vs cross-book matches.
    """
    if not query_words:
        return None, 0.0
    candidates = Counter()
    for w in set(query_words):
        for key in index.get(w, ()):
            candidates[key] += 1
    if not candidates:
        return None, 0.0

    best_key, best_score = None, 0.0
    for key, _ in candidates.most_common(300):
        val = verses[key]
        v_words = val[1] if isinstance(val, tuple) else val
        score = jaccard(query_words, v_words)
        if score > best_score:
            # Apply appropriate threshold
            match_book = key[0]
            is_cross = (match_book != orig_book)
            threshold = thresh_cross if is_cross else thresh_same
            if score >= threshold:
                best_score, best_key = score, key

    return (best_key, best_score) if best_key is not None else (None, 0.0)


# ═══════════════════════════════════════════════════════════════════════════════
# Annotation splitting — v3: tighter, first sentence only, max 20 words
# ═══════════════════════════════════════════════════════════════════════════════

# Pattern to find the first sentence boundary:
# - Period followed by whitespace + capital letter
# - Tilde character
# - Annotation markers: (a), (b), [a], etc. at start of a token
ANNOT_MARKER_RE = re.compile(r'[\(\[][a-z][\)\]]')
SENTENCE_END_RE = re.compile(r'\.(?=\s+[A-Z])')


def split_annotation_v3(text: str):
    """
    v3: Extract ONLY the first sentence as VerseQuote.
    Split at:
      1. First period followed by whitespace + capital letter
      2. First tilde (~)
      3. First annotation marker (a), (b), [a], etc.
    Hard cap: max 20 words. If first sentence > 20 words, truncate to 20.
    Returns (verse_quote, commentary).
    """
    # Find all candidate split points
    split_pos = None

    # Check tilde first (often used as section separator)
    tilde_pos = text.find('~')
    if tilde_pos > 2:
        split_pos = tilde_pos

    # Check annotation marker (a), (b), [a], etc. — must be at word boundary
    m_annot = ANNOT_MARKER_RE.search(text, 2)
    if m_annot:
        pos = m_annot.start()
        if split_pos is None or pos < split_pos:
            split_pos = pos

    # Check sentence end (period + space + capital)
    m_sent = SENTENCE_END_RE.search(text, 2)
    if m_sent:
        pos = m_sent.start() + 1  # just after the period
        if split_pos is None or pos < split_pos:
            split_pos = pos

    if split_pos is not None and split_pos > 2:
        quote = text[:split_pos].strip()
        commentary = text[split_pos:].lstrip(' \t~').strip()
    else:
        # Fallback: first '. ' after at least 10 chars
        fp = text.find('. ', 10)
        if fp > 0:
            quote = text[:fp+1].strip()
            commentary = text[fp+2:].strip()
        else:
            # Last resort: hard cut at 20 words
            words_all = text.split()
            quote = ' '.join(words_all[:20])
            commentary = ' '.join(words_all[20:])

    # Hard cap: max 20 words in VerseQuote
    words = quote.split()
    if len(words) > QUOTE_MAX_W:
        quote = ' '.join(words[:QUOTE_MAX_W])
        # Everything after the cap goes back to commentary
        remainder = ' '.join(words[QUOTE_MAX_W:])
        commentary = (remainder + ' ' + commentary).strip() if commentary else remainder

    return quote.strip(), commentary.strip()


def parse_ref(ref_str):
    m = re.match(r'(\d+):(\d+)', ref_str.strip())
    return (int(m.group(1)), int(m.group(2))) if m else (None, None)


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    # Use bak if it exists (authoritative original)
    src_input = BAK if os.path.exists(BAK) else INPUT
    print(f"Input: {os.path.basename(src_input)}")

    # Load sources
    print("\nLoading verse sources...")
    verses_sd  = load_1609_tsv(SRC_SD)
    verses_odr = load_1609_tsv(SRC_ODR)
    verses_pdf = load_1609_tsv(SRC_PDF)
    verses_drb = load_modern_drb(SRC_DRB)
    print(f"  Source 1 (saint-dismas):  {len(verses_sd):6d} verses  same={THRESH_SD_SAME} cross={THRESH_SD_CROSS}")
    print(f"  Source 2 (originaldouay): {len(verses_odr):6d} verses  same={THRESH_ODR_SAME} cross={THRESH_ODR_CROSS}")
    print(f"  Source 3 (PDF OCR):       {len(verses_pdf):6d} verses  same={THRESH_PDF_SAME} cross={THRESH_PDF_CROSS}")
    print(f"  Source 4 (modern DRB):    {len(verses_drb):6d} verses  same={THRESH_DRB_SAME} cross={THRESH_DRB_CROSS} [match-only]")

    # Build indices
    print("\nBuilding inverted indices...")
    idx_sd  = build_index(verses_sd)
    idx_odr = build_index(verses_odr)
    idx_pdf = build_index(verses_pdf)
    idx_drb = build_index(verses_drb)

    # Books covered by 1609 sources (sources 1-3); rows from uncovered books
    # won't have 1609-text to match against, so LOW_CONFIDENCE is expected
    # and should NOT trigger the abort (they're not algorithmic failures).
    books_1609 = (books_in_source(verses_sd) |
                  books_in_source(verses_odr) |
                  books_in_source(verses_pdf))
    print(f"  Books in 1609 sources: {len(books_1609)}")

    # Load annotations
    print(f"\nReading {os.path.basename(src_input)}...")
    with open(src_input, encoding='utf-8') as f:
        raw_lines = f.readlines()
    ann_rows = []
    for line in raw_lines[1:]:
        parts = line.rstrip('\n').split('\t')
        if len(parts) >= 3:
            ann_rows.append(parts)
    total = len(ann_rows)
    print(f"  {total} annotation rows to process")

    # Process — open output file for incremental writing so abort doesn't lose data
    out_rows      = []
    book_changes  = []
    ref_changes   = []
    low_conf      = []
    bad_splits    = []
    stats         = Counter()
    chk_lc        = 0  # LOW_CONFIDENCE count in current window (covered books only)
    chk_lc_uncov  = 0  # LC count for uncovered books (excluded from abort logic)
    abort_fired   = False

    print(f"\nMatching {total} annotations (v3 — stricter thresholds, tighter split)...\n")
    # Pre-open output file for incremental writing
    out_f = open(OUTPUT, 'w', encoding='utf-8')
    out_f.write("BookAbbrev\tChapter:Verse\tVerseQuote\tCommentary\n")

    for i, parts in enumerate(ann_rows):
        orig_book = parts[0].strip()
        orig_ref  = parts[1].strip() if len(parts) > 1 else ''
        anno_text = parts[2].strip() if len(parts) > 2 else ''

        # Fix abbreviation in original
        orig_book_fixed = fix_abbrev(orig_book)

        # Normalise book alias (Apc → Rev)
        lookup_book = BOOK_ALIAS.get(orig_book_fixed, orig_book_fixed)

        orig_ch, orig_v = parse_ref(orig_ref)

        # v3: tighter split — first sentence, max 20 words
        quote, commentary = split_annotation_v3(anno_text)
        if not quote or len(quote) < 5:
            bad_splits.append((i+1, orig_ref, 'quote too short'))
        if not commentary:
            bad_splits.append((i+1, orig_ref, 'no commentary'))

        q_words = normalize(quote)
        if len(q_words) < 4:
            # too short — extend with a few more words from annotation
            q_words = normalize(anno_text)[:QUOTE_MAX_W]

        # Try sources in order — pass orig_book for threshold discrimination
        match_key, score, via = None, 0.0, ''

        k, s = best_match(q_words, lookup_book, verses_sd,  idx_sd,  THRESH_SD_SAME,  THRESH_SD_CROSS)
        if k:
            match_key, score, via = k, s, 'saint-dismas'

        if not match_key:
            k, s = best_match(q_words, lookup_book, verses_odr, idx_odr, THRESH_ODR_SAME, THRESH_ODR_CROSS)
            if k:
                match_key, score, via = k, s, 'originaldouay'

        if not match_key:
            k, s = best_match(q_words, lookup_book, verses_pdf, idx_pdf, THRESH_PDF_SAME, THRESH_PDF_CROSS)
            if k:
                match_key, score, via = k, s, 'pdf-ocr'

        if not match_key:
            k, s = best_match(q_words, lookup_book, verses_drb, idx_drb, THRESH_DRB_SAME, THRESH_DRB_CROSS)
            if k:
                match_key, score, via = k, s, 'modern-drb'

        # Determine output
        lc_flag = ''
        if match_key:
            new_book, new_ch, new_v = match_key
            stats[f'via_{via}'] += 1
            new_ref = f"{new_ch}:{new_v}"

            # Restore original book alias in output if matched via alias
            if orig_book_fixed in BOOK_ALIAS and BOOK_ALIAS[orig_book_fixed] == new_book:
                new_book = orig_book_fixed

            if new_book != orig_book_fixed:
                book_changes.append((i+1, orig_book_fixed, new_book, orig_ref, new_ref, score, via))
                stats['book_changed'] += 1
            elif new_ref != orig_ref:
                ref_changes.append((i+1, orig_book_fixed, orig_ref, new_ref, score, via))
                stats['ref_changed'] += 1
            else:
                stats['unchanged'] += 1

            final_book = new_book
            final_ref  = new_ref
        else:
            # LOW_CONFIDENCE — keep original (with abbrev fix)
            final_book = orig_book_fixed
            final_ref  = orig_ref
            lc_flag    = ' [LOW_CONFIDENCE]'
            stats['low_conf'] += 1
            # Only count toward abort if the book has 1609 source coverage
            if lookup_book in books_1609:
                chk_lc += 1
            else:
                chk_lc_uncov += 1
            low_conf.append((i+1, orig_book_fixed, orig_ref,
                             f'no match above threshold'))

        row = [
            final_book, final_ref,
            quote.replace('\t', ' '),
            (commentary + lc_flag).replace('\t', ' '),
        ]
        out_rows.append(row)
        out_f.write('\t'.join(row) + '\n')

        # Checkpoint every 200 rows
        if (i + 1) % CHECKPOINT == 0:
            # For abort, use covered-book LC count vs covered rows in window
            covered_in_window = CHECKPOINT - chk_lc_uncov
            if covered_in_window > 0:
                lc_frac = chk_lc / covered_in_window
            else:
                lc_frac = 0.0  # all rows were uncovered books — can't judge
            conf_total = (i + 1) - stats['low_conf']
            book_ch_total = stats['book_changed']
            print(f"  Checkpoint {i+1:4d}/{total} — "
                  f"confident: {conf_total}, low_conf: {stats['low_conf']}, "
                  f"book_changes: {book_ch_total}  "
                  f"| window_lc(covered): {chk_lc}/{covered_in_window} ({lc_frac:.0%})"
                  f"  uncov: {chk_lc_uncov}")
            if lc_frac > ABORT_FRAC:
                print(f"\nWARNING/ABORT signal: {chk_lc}/{covered_in_window} "
                      f"covered-book rows were LOW_CONFIDENCE in last window "
                      f"(>{ABORT_FRAC:.0%} threshold).")
                print(f"  Note: v3 uses stricter thresholds — high LC in windows with")
                print(f"  short/marginal annotations is expected correct behavior.")
                print(f"  Output is written incrementally — continuing to completion.")
                abort_fired = True
            chk_lc = 0
            chk_lc_uncov = 0

    # Close incremental output file
    out_f.close()

    # Final summary
    print(f"\n{'='*60}")
    print(f"RESULTS  (total={total})")
    for k in sorted(stats.keys()):
        print(f"  {k}: {stats[k]}")
    if abort_fired:
        print(f"\n  [ABORT SIGNAL FIRED — see warnings above — output is complete]")

    print(f"\nOutput already written to {os.path.basename(OUTPUT)} (incremental).")

    # Write report
    print(f"Writing {os.path.basename(REPORT)} ...")
    with open(REPORT, 'w', encoding='utf-8') as f:
        w = f.write
        w("=" * 70 + "\n")
        w("DOUAI 1609 ANNOTATION FIX REPORT v3\n")
        w("=" * 70 + "\n\n")
        w("v3 CHANGES vs v2:\n")
        w("  - VerseQuote: first sentence only, hard cap 20 words (was 30)\n")
        w("  - Cross-book threshold: 0.40 for sources 1-3 (was 0.25)\n")
        w("  - Modern DRB thresholds: same-book 0.35, cross-book 0.50 (was 0.20)\n")
        w("  - Checkpoint abort: >70% LOW_CONF (was >60%)\n")
        w("  - Abbreviation normalization: 2Sm→2Sam, 2Kgs→2Kings, etc.\n\n")
        w("SUMMARY\n" + "-"*40 + "\n")
        w(f"Total annotation rows:          {total}\n")
        via_total = sum(v for k,v in stats.items() if k.startswith('via_'))
        w(f"Matched (confident):            {via_total} ({via_total/total*100:.1f}%)\n")
        for src in ('saint-dismas','originaldouay','pdf-ocr','modern-drb'):
            n = stats.get(f'via_{src}', 0)
            w(f"  via {src:20s}: {n}\n")
        w(f"LOW_CONFIDENCE (kept):          {stats['low_conf']} ({stats['low_conf']/total*100:.1f}%)\n")
        w(f"Book changed:                   {stats['book_changed']}\n")
        w(f"Ref changed (same book):        {stats['ref_changed']}\n")
        w(f"Ref unchanged:                  {stats['unchanged']}\n")
        w(f"\nThresholds:\n")
        w(f"  Source 1 (saint-dismas):  same={THRESH_SD_SAME}  cross={THRESH_SD_CROSS}\n")
        w(f"  Source 2 (originaldouay): same={THRESH_ODR_SAME} cross={THRESH_ODR_CROSS}\n")
        w(f"  Source 3 (pdf-ocr):       same={THRESH_PDF_SAME} cross={THRESH_PDF_CROSS}\n")
        w(f"  Source 4 (modern-drb):    same={THRESH_DRB_SAME} cross={THRESH_DRB_CROSS} [match-only]\n")
        if abort_fired:
            w(f"\nNOTE: Abort signal fired during run (>70% LC in a covered-book window).\n")
            w(f"  This was due to strict v3 thresholds correctly rejecting false positives\n")
            w(f"  in sections with short/marginal annotations. Output is complete.\n")
        w(f"\nHard rule: modern DRB text NEVER appears in output TSV.\n")
        w(f"  VerseQuote = annotation's own original text (first sentence, ≤20 words).\n")
        w(f"  Commentary = annotation's own original text (remainder after split).\n")

        w("\n" + "="*70 + "\n")
        w("SECTION A: BOOK-LEVEL CORRECTIONS\n")
        w("="*70 + "\n")
        w(f"({len(book_changes)} rows where book changed)\n\n")
        for row_i, ob, nb, or_, nr, sc, via in book_changes:
            w(f"  Row {row_i:4d}: {ob:8s} {or_:8s} → {nb:8s} {nr:8s}  [score={sc:.3f} via={via}]\n")

        w("\n" + "="*70 + "\n")
        w("SECTION B: CHAPTER/VERSE CORRECTIONS (SAME BOOK)\n")
        w("="*70 + "\n")
        w(f"({len(ref_changes)} rows)\n\n")
        for row_i, ob, or_, nr, sc, via in ref_changes:
            w(f"  Row {row_i:4d}: {ob:8s} {or_:8s} → {nr:8s}  [score={sc:.3f} via={via}]\n")

        w("\n" + "="*70 + "\n")
        w("SECTION C: LOW_CONFIDENCE ROWS (original ref kept)\n")
        w("="*70 + "\n")
        w(f"({len(low_conf)} rows)\n\n")
        for row_i, ob, or_, reason in low_conf:
            w(f"  Row {row_i:4d}: {ob:8s} {or_:12s} — {reason}\n")

        w("\n" + "="*70 + "\n")
        w("SECTION D: SPLIT ISSUES\n")
        w("="*70 + "\n")
        w(f"({len(bad_splits)} flags)\n\n")
        for row_i, or_, reason in bad_splits:
            w(f"  Row {row_i:4d}: {or_:12s} — {reason}\n")

    print(f"\nDone.")
    print(f"  Output:  {OUTPUT}")
    print(f"  Report:  {REPORT}")


if __name__ == '__main__':
    main()
